---

- name: Update ubuntu servers
  hosts: kworker:kmaster
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        upgrade: yes
        state: latest

- name: Prepare K8S
  hosts: kworker:kmaster
  become: yes
  tasks:
    - name: Turn off SWAP
      ansible.builtin.command: sudo swapoff -a
    - name: Install packages > apt-transport-https ca-certificates curl lsb-release
      ansible.builtin.apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - lsb-release
    - name: Get keys K8S
      ansible.builtin.command: sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - name: Install keys K8S
      become: yes
      shell: sudo echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      args:
        creates: "/etc/apt/sources.list.d/kubernetes.list"
    - name: Install packages > kubelet kubeadm kubectl
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - kubelet
        - kubeadm
        - kubectl

- name: Set hostname MasterNode
  hosts: kmaster
  become: yes
  tasks:
    - name: Set MasterNode hostname
      ansible.builtin.command: sudo hostnamectl set-hostname KMasterNode

- name: Set hostname KWorkerNode
  hosts: kworker
  become: yes
  tasks:
    - name: Set WorkerNode hostname      
      ansible.builtin.command: sudo hostnamectl set-hostname KWorkerNode
